language: node_js
node_js:
  - "node"

branches:
  only:
    - master
    - /^greenkeeper/.*$/

before_script:
  - npm install -g firebase-tools

script:
  - npm run build

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "wBIi25gafavHVmMljtvIIlLd8l6rvBEszoE77iECfBF5Juglgi3QLvNxQShG/o8KpQZeZ9IOOhuHYyepUxXw7vsKDC5+3gSlCYiJS3spdP9RKv0T8kLOGI2qB1c+u2WeS8K0rqRGh3VYVpg27K5Z+svS48aqLOLVUJKHtOT7pWO7Q7wb4W9y6BOSCpE2zc06OrSpVZ1SeGSbQddjv4PStihlYIY+8g2DBrRhGUktktxYaSEqn57qNfW+rLNkJW8EBibvew7xdHDc8Ky1WF85Ivw5OnWcui8/wsXPHgT7XkX6AVfRMZtio8mKh4BkcNTQFsY3wGhn82auZ8AnH0IKSunoOgglKKjmYDFxnNcvErNa0m5v/1fkvuA5qcaJ9XkcdgW7Jmvl6Ea/ecDP17IDOI7iTAHk5pUJ9rzspfasdwUehVPL1LLtQ2FMajM5a1VhJxwBPje4cUjHTFNkkbyFLuCR2iJhfKy9pVB5WYBhs/pgKjmgaB9aT9MPPXHxNd6qsWYkUJt+XJn+BLD9I2t13o7rAPXAHcr6eXoObl2mRvpMH57g/w0qUPF41AoRQhqQAxHQ1iaS7Oppu5rxMqGKZJTVj76F06LdWvLqOz+fwq6a2DVpxWz90T1R+lsywjLmM2pzI0fUGy8Z4WBrCqsk9bZkrQ6+qa3LDv5Vdl5gVv4="

notifications:
  email:
    on_failure: change
    on_success: change
